# iPhone 
iphone_image:
  "Image Size": "2048x1536"
  "Make": "Apple"
  "Model": "iPhone"
  "File Type": "JPEG"
# iPhone 4S
iphone4s_video:
  "File Type": "MOV"
  "Model": "iPhone 4S"
  "Image Size": "1920x1080"
iphone4s_video_front:
  "File Type": "MOV"
  "Model": "iPhone 4S"
  "Image Size": "640x480"
iphone4s_image:
  "File Type": "JPEG"
  "Model": "iPhone 4S"
  "Image Size": "3264x2448"
iphone4s_image_front:
  "File Type": "JPEG"
  "Model": "iPhone 4S"
  "Image Size": "640x480"
# iPhone 6
iphone6_video:
  "File Type": "MOV"
  "Model": "iPhone 6"
  "Image Size": "1920x1080"
iphone6_video_front:
  "File Type": "MOV"
  "Model": "iPhone 6"
  "Image Size": "1280x720"
iphone6_image:
  "File Type": "JPEG"
  "Model": "iPhone 6"
  "Image Size": "3264x2448"
iphone6_image_square:
  "File Type": "JPEG"
  "Model": "iPhone 6"
  "Image Size": "2448x2448"
iphone6_image_front:
  "File Type": "JPEG"
  "Model": "iPhone 6"
  "Image Size": "1280x960"
# Samsung Galaxy SII Skyrocket
galaxy_s2_video:
  "Image Size": "1920x1080"
  "File Type": "MP4"
galaxy_s2_image:
  "Model": "SGH-I727"
  "Image Size": "3264x2448"
  "File Type": "JPEG"
galaxy_s2_image_front:
  "Model": "SGH-I727"
  "Image Size": "1600x1200"
  "File Type": "JPEG"
#
galaxy_s5_image:
  "Image Size": "2048x1152"
  "Make": "SAMSUNG"
  "Model": "SAMSUNG-SM-G900A"
  "File Type": "JPEG"
galaxy_s5_image_hi:
  "Image Size": "5312x2988"
  "Make": "SAMSUNG"
  "Model": "SAMSUNG-SM-G900A"
  "File Type": "JPEG"
galaxy_s5_image_front:
  "Image Size": "1920x1080"
  "Make": "SAMSUNG"
  "Model": "SAMSUNG-SM-G900A"
  "File Type": "JPEG"

